export const IMAGES = {
    FUJIMA_LOGO: require('../assets/pngs/fujima.png'),
    EYE: require('../assets/pngs/eye.png'),
    LEFT_ARROW: require('../assets/pngs/left.png'),
    FULL_BLUE_CIRCLE: require("../assets/pngs/ellipseblue.png"),
    FULL_GRAY_CIRCLE: require("../assets/pngs/ellipsegray.png"),
    HALF_GREEN_CIRCLE: require("../assets/pngs/ellipsegreen.png"),
    HALF_BLUE_CIRCLE: require("../assets/pngs/halfblue.png"),
    UPLOAD_FILE:require("../assets/pngs/uploadfilebackground.png"),
    CLOUD:require("../assets/pngs/cloud.png"),
    DELETE:require("../assets/pngs/delete2.png"),
    HOME:require("../assets/pngs/home.png"),
    MAIL:require("../assets/pngs/mail.png"),
    SPLASH:require("../assets/pngs/splash.png"),
    SPLASH0:require("../assets/pngs/splash0.png"),
    BANNER:require("../assets/pngs/banner.png"),
    SEARCH:require("../assets/pngs/search.png"),
    QR:require("../assets/pngs/qr.png"),
    PRODUCTBANNER:require("../assets/pngs/productbanner.png"),
    HEART:require("../assets/pngs/heart.png"),
    REQUESTED_PIC:require("../assets/pngs/requestedpic.png"),
    BRANDS:require("../assets/pngs/brands.png"),
    SHOPBANNER:require("../assets/pngs/shopBanner.png"),
    USER_DETAIL:require("../assets/pngs/userdetails.png"),
    CONTACT_DETAIL:require("../assets/pngs/contactdetails.png"),
    VERIFY:require("../assets/pngs/verified.png"),
    APPAREL:require('../assets/pngs/Apparel.jpg'),
    ART:require('../assets/pngs/Art.jpg'),
    CIGAR:require('../assets/pngs/cigar.png'),
    CLANING:require('../assets/pngs/Cleaning.jpg'),
    CIGRATTE:require('../assets/pngs/cigarette.png'),
    ASHTRAYS:require('../assets/pngs/Ashtrays.jpg'),
    CLEARANCE:require('../assets/pngs/CLEARANCE.jpg'),
    CSTORE:require('../assets/pngs/c-store.png'),
    STOREG:require('../assets/pngs/storage.png'),
    SPITTOONS:require('../assets/pngs/Spittoons.jpg'),
    ROLL:require('../assets/pngs/roll.png'),
    PIPES:require('../assets/pngs/pipes.png'),
    PREPACK:require('../assets/pngs/prepack.png'),
    NOVELITY:require('../assets/pngs/Novelty.jpg'),
    LIGHTERS:require('../assets/pngs/Lighters.jpg'),
    KITCHEN:require('../assets/pngs/Kitchen.jpg'),
    HOOKAHAH:require('../assets/pngs/hookah.png'),
    ELECTRONIC:require('../assets/pngs/electronic.png'),
    DEALS:require('../assets/pngs/DEALS.jpg'),
    APRELBANNER:require('../assets/pngs/aprelbanner.jpg'),
    DEFAULT:require('../assets/pngs/default.jpg'),
    FUJIMA_SPLASH:require('../assets/pngs/fujima-logo.gif'),
    SHOP:require('../assets/pngs/shop.png'),
    CART:require('../assets/pngs/cart.png'),
    SAVE:require('../assets/pngs/save.png'),
    REMOVE:require('../assets/pngs/remove.png')
}
